{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "collapsed_sections": [
        "oTvNzYU3qDf4",
        "Bh0x1O9lVIMf",
        "wXx0MoA1m0K8",
        "LenrMJf2DkI0",
        "JhbSo-mJRJ5c",
        "_CYAZ1KL0p1u",
        "CQ6WOe7BWhm1"
      ]
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# AWS CLOUD PRACTITIONER CERTIFICATION"
      ],
      "metadata": {
        "id": "F4RJsDZXp0-n"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 1. WHAT IS CLOUD COMPUTING?"
      ],
      "metadata": {
        "id": "oTvNzYU3qDf4"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**SERVER**\n",
        "* CPU (Compute)\n",
        "* RAM (Memory)\n",
        "* Data (Storage) \n",
        "* Database (Store data in structured way)\n",
        "* Network (Cables, routers and servers connected with each other)\n",
        "* Router (A networking device that forwards data packets between computer networks. They know where to send your packets on the internet)\n",
        "* Switch (Takes a packet and send it to the correct server/client on your network)\n",
        "\n",
        "<br>\n",
        "\n",
        "**PROBLEMS WITH TRADITIONAL IT APPROACH**\n",
        "* Pay for the rent for the data center\n",
        "* Pay for power supply, cooling, maintenance \n",
        "* Adding and replacing hardware takes time\n",
        "* Scaling is limited \n",
        "* Hire 24/7 team to monitor the infrastructure \n",
        "* How to deal with disasters? (earthquake, power shutdown, fire)\n",
        "\n",
        "<br>\n",
        "\n",
        "**CLOUD COMPUTING**\n",
        "* On demand delivery of compute power, database storage, applications, IT services\n",
        "* Pay-as-you-go pricing  \n",
        "* Provision exactly the right type and size of computing resources you need\n",
        "* Access many resources as you need, almost instantly\n",
        "* Simply way to access servers, storage, databases abd set of application services\n",
        "\n",
        "<br>\n",
        "\n",
        "**DEPLOYMENT MODELS OF THE CLOUD**\n",
        "* *PRIVATE CLOUD*: \n",
        "  * Cloud used by single organization, not exposed to the public\n",
        "  * Complete control\n",
        "  * Security for sensitive application\n",
        "  * Meet specific business needs\n",
        "* *PUBLIC CLOUD*:\n",
        "  * Cloud resources owned and operated by a third-part cloud service provider delivered on the internet\n",
        "  * 6 advantages of cloud computing  \n",
        "* *HYBRID CLOUD*:\n",
        "  * Keep some servers on premises and extend some capabilities to the cloud\n",
        "  * Control over sensitive assets in your private infrastructure\n",
        "  * Flexibility and cost effectiveness of the public cloud  \n",
        "\n",
        "<br>\n",
        "\n",
        "**THE 5 CHARACTERISTICS OF CLOUD COMPUTING** \n",
        "* *On demand self service*: Users can provision resources and use them without human interaction from the service provider\n",
        "* *Broad network access*: Resources available over the network\n",
        "* *Multi-tenancy and resource pooling*: Multiple customers can share the same infrastructure with security and privacy and they are serviced from the same physical resources\n",
        "* *Rapid elasticity and scalability*: Automatically and quickly acquire and dispose resources when needed and easily scale based on demand\n",
        "* *Measured service*: Usage is measured, users pay correctly for what they have used\n",
        "\n",
        "<br>\n",
        "\n",
        "**THE 6 ADVANTAGES OF CLOUD COMPUTING**\n",
        "* *Trade capital expense (CAPEX) for operational enpense (OPEX)*: Pay on demand, don't own hardware and reduce total cost of ownership\n",
        "* *Benefit from massive economies of scale*: Prices are reduced as AWS is more efficient due to large scale\n",
        "* *Stop guessing capacity*: Scale based on actual measured usage\n",
        "* *Increase speed and agility*\n",
        "* *Stop spending money running and maintaining data centers*\n",
        "* *Go global in minutes*\n",
        "\n",
        "<br>\n",
        "\n",
        "**PROBLEMS SOLVED BY THE CLOUD**\n",
        "* *Flexibility*: Change resource types when needed\n",
        "* *Cost-Effectiveness*: Pay as you go for what you use\n",
        "* *Scalability*: Accomodate larger loads by making hardware stronger or adding additional nodes\n",
        "* *Elasticity*: Ability to scale out and scale-in when needed\n",
        "* *High available and fault tolerance*: Build across data centers\n",
        "* *Agility*: Rapidly develop, test and launch software application\n",
        "\n",
        "<br>\n",
        "\n",
        "**TYPES OF CLOUD COMPUTING**\n",
        "* *Infrastructure as a Service (EC2)*:\n",
        "  * Provide bulding blocks for cloud IT\n",
        "  * Provides networking, computers, data storage space\n",
        "  * Highest level of flexibility\n",
        "  * Easy parallel with traditional on-premises IT\n",
        "* *Platform as a Service (Elastic Beanstalk)*:\n",
        "  * Removes the need for your organization to manage the underlying infrastructure\n",
        "  * Focus on the deployment and management of your applications\n",
        "* *Software as a Service (Rekognition, Google Maps)*:\n",
        "  * Completed product that is run and managed by the service provider\n",
        "\n",
        "<br>\n",
        "\n",
        "**PRICING OF THE CLOUD**\n",
        "* *Compute*: Pay for compute time\n",
        "* *Storage*: Pay for data stored in the Cloud\n",
        "* *Data Transfer OUT*: Data transfer IN is free\n",
        "\n",
        "<br>\n",
        "\n",
        "**AWS GLOBAL INFRASTRUCTURE**\n",
        "* *AWS REGION*\n",
        "  * Region all around the world (us-east-1, eu-west-3)\n",
        "  * Cluster of data centers\n",
        "  * Most AWS services are region-scoped (*IAM*, *Route 53*, *WAF*: examples of global services)\n",
        "  * Choose the region according to the data governance and legal requirements\n",
        "  * Proximity to customers to reduce latency\n",
        "  * Available services within a region\n",
        "  * Pricing which can vary from a region to another\n",
        "\n",
        "<br>\n",
        "\n",
        "* *AWS AVAILABILITY ZONES*\n",
        "  * Each region has many availability zones (min 2, max 6, usually 3)\n",
        "  * Each AZ is one or more discrete ddata ccenters with redundant power\n",
        "  * They're isolated from disasters\n",
        "  * They're connected with high bandwidth, ultra-low latency\n",
        "\n",
        "<br>\n",
        "\n",
        "* *AWS POINT OF PRESENCE (EDGE LOCATIONS)*\n",
        "  * Amazon has 216 points of presencein 84 cities and 42 countries\n",
        "  * Content is delivered to end user with lower latency  \n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "8ESmSpVVqMhF"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 2. IAM SECTION"
      ],
      "metadata": {
        "id": "Bh0x1O9lVIMf"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**IAM: Identity and Access Management**\n",
        "* *USERS*: They are people within your organization and can be grouped. There is a root account created by default and it shouldn't be used or shared.\n",
        "* *GROUPS*: They only contains users, not other groups and users don't have to belong to a group and can belong to multiple groups.\n",
        "* *POLICIES*: Users or groups can be assigned JSON documents called policies. These policies define the permission of the users. In AWS you apply the least privilege principle, don't give more permission than a user needs.\n",
        "* *SECURITY*: Password policy + MFA (Multi Factor Authentication).\n",
        "* *AWS CLI*: Manage your AWS services by the command line. Direct access to the public APIs of AWS services. Alternative to AWS Management Console.\n",
        "* *AWS SDK*: Manage your AWS services using a programming language (Software Development Kit) with language specific APIs.\n",
        "* *Access Keys*: To access AWS using the CLI or SDK. They are generated through the AWS Management Console and they are like a password.\n",
        "* *IAM ROLES*: They are just like a user but they are intended to be used not by physical people but instead they will be used by AWS services that need to perform actions on your behalf (EC2, Lambda).\n",
        "* *IAM SECURITY TOOLS*: IAM Credentials Report that lists all your account's users and the status of the various credentials and IAM Access Advisor which shows the service permissions granted to a userand when those services were last accessed. "
      ],
      "metadata": {
        "id": "c6tLgrePVUa5"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 3. EC2 SECTION"
      ],
      "metadata": {
        "id": "wXx0MoA1m0K8"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**EC2: Elastic Compute Cloud**\n",
        "\n",
        "<br>\n",
        "\n",
        "**EC2**\n",
        "\n",
        "It mainly consists in the capability of:\n",
        "* Renting virtual machines (EC2)\n",
        "* Storing data on virtual drives (EBS)\n",
        "* Distributing load across machines (ELB)\n",
        "* Scaling the services using an auto-scaling group (ASG)\n",
        "\n",
        "**EC2 Configuration**\n",
        "* Operating System: Linux, Windows or MacOS\n",
        "* How much compute power & cores (CPU)\n",
        "* How much random-access memory (RAM)\n",
        "* How much storage space:\n",
        "  * Network attached (EBS & EFS)\n",
        "  * Hardware (EC2 Instance Store)\n",
        "* Network Card: speed of the card, Public IP address\n",
        "* Bootstrap script (configure at first launch): EC2 User Data  \n",
        "\n",
        "**EC2 Instance Types**\n",
        "\n",
        "* m5.2xlarge (e.g.):\n",
        "  * *m*: Instance class\n",
        "  * *5*: Generation (AWS improves over time)\n",
        "  * *2xlarge*: Size within the instance class\n",
        "* *General Purpose*: Great for a diversity of workloads such as web servers or code repositories. Balance between compute, memory and networking.\n",
        "* *Compute Optimized*: Great for compute intensive tasks that require high performance processors as batch processing workloads, scientific model and machine learning or gaming servers.\n",
        "* *Memory Optimized*: Fast performance for workloads that process large data sets in memory as high perf relational/non-relational databases or distributed web scale cache stores.\n",
        "* *Storage Optimized*: Great for storage intensive tasks that require high, sequential read and write access to large data sets on local storage as cache for in memory databases (Redis).\n",
        "\n",
        "**EC2 Security Groups**\n",
        "\n",
        "Security groups are acting as a firewall on EC2 instances, they control how traffic is allowed into or out our EC\" instances. Security groups only contain allow rules and can reference by IP or by security group. They regulate:\n",
        "\n",
        "* Access to ports\n",
        "* Authorized IP ranges - IPv4 and IPv6\n",
        "* Control of inbound network (from other to instance, blocked by default)\n",
        "* Control of outbound network (from instance to other, authorized by default)\n",
        "\n",
        "**EC2 User Data**\n",
        "\n",
        "It's possible to bootstrap (launching commands when a machine start) ourinstances using an EC2 User Data script. That script is only run once at the instance first start and it run with the root user. It's used to automate boot tasks such as:\n",
        "* Installing updates\n",
        "* Installing software\n",
        "* Downloading common files from internet\n",
        "* Anything you can think of\n",
        "\n",
        "**SSH**\n",
        "\n",
        "It allows you to control a remote machine, all using the command line. We can configure all the parameters using the free tool \"Putty\".\n",
        "\n",
        "**Purchasing Options**\n",
        "\n",
        "* *EC2 On-Demand Instances*: Linux/Windows billing per seconds after the first minute, otherwise billing per hour. Has the highest cost but no upfront payment. No long-term commitment and recommended for short term and un-interrupted workloads.\n",
        "* *EC2 Reserved Instances*: Uo to 72% discount (compared to on-demand). You reserve a specific instance attributes (instance type, region, tenancy, OS) with a reservation period of 1 or 3 years with different payment options:\n",
        "  * No Upfront (+)\n",
        "  * Partial Upfront (++)\n",
        "  * All Upfront (+++)\n",
        "You can reserve an instance scope, regional or zonal and it's recommended for steady-state usage applications (db) and you can buy and sell in the Reserved Instance Marketplace.\n",
        "* *EC2 Convertible Reserved Instance*: Can change EC2 instance type, instance family, OS, scope and tenancy and you can get up to 66% of discount.\n",
        "* *EC2 Saving Plans*: Get a discount based on long-term usage and commit to a certain type of usage (e.g. $10/hour for 1/3 years), usage beyond EC\" Saving Plans is billed at the on-demand rate. It's flexible across instance size, OS and tenancy.\n",
        "* *EC2 Spot Instances*: Instances that you can lose at any point of time if your max price is less than the current spot price. It's the most cost-efficient instances in AWS and you can get a discount of up to 90% compared to on-demand. It's useful for workload that are resilient to failure as batch jobs, data analysis or image processing and it's not suitable for critical jobs or databases.\n",
        "* *EC2 Dedicated Hosts*: A physical server with EC2 instance capacity fully dedicated to your use, that's the most expensive option. Purchasing option:\n",
        "  * On-demand: pay per second for active Dedicated Host\n",
        "  * Reserved: 1 or 3 years (No/Partial/All Upfront)\n",
        "* *EC2 Dedicated Instances*: Instance run on hardware that's decicated to you, you may share hardware with other instances in same account and there is no control over instance placement (can move hardware after stop/start).  \n",
        "* *EC2 Capacity Reservations*: Reserve on-demand instances capacity in a specific AZ for any duration. No time commitment or billing discount. You are charged at on-demand rate whether you run instances or not. Suitable for short term, uninterrupted workloads that needs to be in a specific AZ.\n",
        "\n",
        "**Best Purchasing Option**\n",
        "\n",
        "* *On-Demand*: Coming and staying in resort whenever we like, we pay the full price\n",
        "* *Reserved*: Like planning ahead and if we plan to stay for a long time, we may get a good discount.\n",
        "* *Saving Plans*: Pay a certain amount per hour for certain period and stay in any room type (e.g. King, Suite, Sea View, etc...)\n",
        "* *Spot Instances*: The hotel allows people to bid for the empty rooms and the highest bidder keeps the rooms. You can get kicked out at any time.\n",
        "* *Dedicated Host*: We book an entire building of the resort.\n",
        "* *Capacity Reservations*: You book a room for a period with full price even you don't stay in it.\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "6Uy6I3U0m60W"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 4. EC2 INSTANCE STORAGE SECTION"
      ],
      "metadata": {
        "id": "LenrMJf2DkI0"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**EBS VOLUME: Elastic Block Store**\n",
        "* What is an EBS?\n",
        "  * It's a network drive you can attach to your instances while they run\n",
        "  * It allows your instances to persist data, even after termination\n",
        "  * They can only be mounted to one instance at a time\n",
        "  * They are bound to a specific availability zone: to move a volume across, you first need to snapshot it\n",
        "  * Free tier = 30GB of storage (you can increase the capacity of the drive over time)\n",
        "  * Analogy: Think of them as a \"Network USB stick\" (not a physical drive) \n",
        "* EBS Snapshots\n",
        "  * *Snapshot* = Backup of your EBS volume at a point in time\n",
        "  * Not necessary to detach volume to do snapshot but recommended\n",
        "  * Can copy snapshots across AZ or Region\n",
        "  * *EBS Snapshot Archive*: move a snapshot to an \"archive tier\" that is 75% cheaper but it takes within 24 to 72 hours for restoring the archive\n",
        "  * You can setup rules to retain deleted snapshots so you can recover them after an accidental deletion (you can specify retention from 1 day to 1 year)\n",
        "\n",
        "**AMI: Amazon Machine Image**\n",
        "* Ready to use EC2 instances with our customization (own software, configuration, operating system, monitoring)\n",
        "* AMI are built for a specific region ( and can be copied across regions)\n",
        "* You can launch EC2 instances from:\n",
        "  * Public AMI: AWS provided\n",
        "  * Your own AMI: you make and mantain them yourself\n",
        "  * AWS Marketplace AMI: AMI someone else made \n",
        "* *AMI Process*:\n",
        "  * Start an EC2 instance and customize it\n",
        "  * Stop the instance\n",
        "  * Build an AMI - this will also create an EBS Snapshot\n",
        "  * Launch instances from other AMIs\n",
        "\n",
        "**EC2 Image Builder**\n",
        "* Used to automate the creation of Virtual Machines or container images\n",
        "* Automate creation, mantain, validate and test of EC2 AMIs\n",
        "* Can be run on a schedule\n",
        "* Free service (only pay for the underlying resources)\n",
        "\n",
        "**EC2 Instance Store**\n",
        "* EBS volumes are network drives with good but limited performance\n",
        "* If you need a high performance hardware disk, use *EC2 Instance Store*\n",
        "* Better I/O performance\n",
        "* EC2 Instance Store lose their storage if they're stopped\n",
        "* Risk of data loss if hardware fails\n",
        "* Good for buffer/cache/scratch data/temporary content\n",
        "\n",
        "**EFS: Elastic File System**\n",
        "* Managed NFS (network file system) that can be mounted on 100s of EC2\n",
        "* EFS works with Linux EC2 insyances in multi-AZ\n",
        "* Highly available, scalable, expensive, pay per use\n",
        "\n",
        "**EFS-IA: EFS Infrequent Access**\n",
        "* Storage class that is cost-optimized for files not accessed every day\n",
        "* Up to 92% lower cost compared to EFS standard\n",
        "* EFS will automatically move your files to EFS-IA based on last time they were accessed\n",
        "\n",
        "**Amazon FSx**\n",
        "\n",
        "Launch 3rd party high-performance file system on AWS\n",
        "* *Amazon FSx for Windows*\n",
        "  * A fully managed, highly reliable and scalable Windows native shared file system\n",
        "  * Build on Windows File Server\n",
        "  * Supports SMB protocol & windows NTFS\n",
        "  * Integrated with Microsoft Active Directory\n",
        "* *Amazon FSx for Lustre*\n",
        "  * A fully managed, high-performance, scalable file storage for HPC (High Performance Computing)\n",
        "  * The name \"Lustre\" derive from \"Linux\" and \"cluster\"\n",
        "  * Machine Learning, Analytics, Video Processing, Financial Modeling...\n",
        "  * Scales up to 100s GB/s, sub-ms latencies\n"
      ],
      "metadata": {
        "id": "uM_sQWFjDo8I"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 5. ELASTIC LOAD BALANCING & AUTO SCALING GROUPS SECTION"
      ],
      "metadata": {
        "id": "JhbSo-mJRJ5c"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**Scalability vs High Availability**\n",
        "* *Scalability*\n",
        "  * It means an application/system can handle greater loads by adapting\n",
        "  * It's linked but different to High Availability\n",
        "  * Vertical Scalability\n",
        "    * It means increase the size of the instance\n",
        "    * It is very common for non distributed systems, such as database\n",
        "    * There's usually a limit to how much you can vertically scale (hardware limit)\n",
        "  * Horizontal Scalability\n",
        "    * It means increase the number of instances/systems for your application\n",
        "    * It implies distributed systems\n",
        "    * This is very common for web applications/modern applications\n",
        "    * It's easy to horizontally scale thanks the cloud offerings such as Amazon EC2\n",
        "* *High Availability*\n",
        "  * It goes hand in hand with horizontal scaling\n",
        "  * It means running your application in at least 2 AZs\n",
        "  * The goal of high availability is to survive a data center loss (disaster)\n",
        "\n",
        "**Scalability vs Elasticity vs Agility**\n",
        "* *Scalability*: ability to accomodate a larger load by making the hardware stronger (scale up) or by adding nodes (scale out)\n",
        "* *Elasticity*: once a system is scalable, elasticity means that there will be some auto-scaling so that the system can scale based on the load (cloud friendly)\n",
        "* *Agility*: (distractor) new IT resources are only a click away, which means that you reduce the time to make those resources available to your developers\n",
        "\n",
        "**ELB: Elastic Load Balancer**\n",
        "* Distribute traffic across backend EC2 instances, can be multi AZ\n",
        "* Expose a single point of access (DNS) to your application\n",
        "* Do regular health checks to your instances \n",
        "* It's a managed load balancer: AWS guarantees that it will be working, takes care of upgrades and maintenance and provides only a few config knobs\n",
        "* Kind of load balancers offered by AWS:\n",
        "  * Application Load Balancer: HTTP/HTTPS (Layer 7)\n",
        "  * Network Load Balancer: ultra high-perf, TCP (Layer 4)\n",
        "  * Classic Load Balancer: slowly retiring (Layer 4 & 7)\n",
        "\n",
        "**ASG: Auto Scaling Groups**\n",
        "* Implement Elasticity for your application, accross multiple AZ\n",
        "* Scale EC2 instances based on the demand on your system and replace unhealthy\n",
        "* Integrated with the ELB\n",
        "* Scaling strategies:\n",
        "  * Manual scaling: update size manually\n",
        "  * Simple/Step Scaling: when a CloudWatch alarm is triggered then do something  \n",
        "  * Target Tracking Scaling: e.g. I want avg ASG CPU to stay at around 40%\n",
        "  * Scheduled Scaling: anticipate scaling \n",
        "  * Predictive Scaling: ML to predict future traffic ahead of time\n"
      ],
      "metadata": {
        "id": "dCdog33MRUIL"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 6. AMAZON S3 SECTION"
      ],
      "metadata": {
        "id": "_CYAZ1KL0p1u"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "*Amazon S3* is one of the main building blocks of AWS, it's advertised as \"infinitely scaling\" storage. It has a lot of use cases as backup and storage, disaster recovery, archive, application hosting, big data analytics, software delivery and static website.\n",
        "\n",
        "**Buckets vs Objects**\n",
        "* Buckets:\n",
        "  * Amazon S3 allows people to store objects (files) in \"buckets\" (directories)\n",
        "  * They must have a globally unique name \n",
        "  * They are at the region level\n",
        "  * S3 looks like a global service but buckets are created in a region\n",
        "  * There is a naming convention (no uppercase/underscore, 3-63 chars long, start with lowercase or number, etc...)\n",
        "* Objects:\n",
        "  * Object (files) have a key which is a full path (prefix + object name) e.g. s3://my-bucket/my_file.txt\n",
        "  * There is no concept of directories within buckets\n",
        "  * Max size is 5000GB and if uploading more than 5GB must use multi part upload\n",
        "  * Tags: useful for security/lifecycle\n",
        "  * Version ID: if versioning is enabled\n",
        "\n",
        "**S3 Security**\n",
        "* User Based:\n",
        "  * IAM Policies: which API calls should be allowed for a specific user from IAM\n",
        "* Resource-Based:\n",
        "  * Bucket Policies: bucket wide rules from the S3 console - allow cross account\n",
        "  * Object Access Control List: finer grain\n",
        "  * Bucket Access Control List: less common\n",
        "* Note: an IAM principal can access an S3 if \n",
        "  * The user IAM permission allow it or the resource policy allows it\n",
        "  * And there is no explicit deny   \n",
        "* Policies:\n",
        "  * JSON based policies\n",
        "    * Resources: buckets and objects\n",
        "    * Effect: Allow/Deny\n",
        "    * Actions: Set of API to allow or deny\n",
        "    * Principal: The account or user to apply the policy to\n",
        "  * S3 bucket for policy:\n",
        "    * Grant public access to the bucket\n",
        "    * Force objects to be encrypted at upload\n",
        "\n",
        "**S3 Websites**\n",
        "* S3 can host a static websites and have them accessible on the internet\n",
        "* The website URL depend on the bucket name and region         \n",
        "* 403 forbidden error --> make sure the bucket policy allows public reads\n",
        "\n",
        "**S3 Versioning**\n",
        "* You can version files in Amazon S3\n",
        "* It's enabled at the bucket level\n",
        "* It's best practice to protect against unintended deletes and easy roll back to previous version\n",
        "\n",
        "**S3 Replication**\n",
        "* Must enable versioning in source and destination buckets\n",
        "* Cross-Region Replication (CRR): lowerlatency access,replication across accounts\n",
        "* Same-Region Replication (SRR): log aggregation, live replication between production and test accounts\n",
        "\n",
        "**S3 Storage Classes**\n",
        "* *S3 Standard - General Purpose*\n",
        "  * 99.99% availability\n",
        "  * Used for frequently accessed data\n",
        "  * Low latency\n",
        "  * Use case: big data analytics, mobile and game applications\n",
        "* *S3 Standard - Infrequent Access (IA)*\n",
        "  * For data less accessed, but requires rapid access when needed\n",
        "  * Lower cost than S3 standard\n",
        "  * 99.9% availability\n",
        "  * Use cases: disaster recovery and backups\n",
        "* *S3 One-Zone - Infrequent Access*\n",
        "  * High durability (99.999999%) in a single AZ. Data lost if AZ is destroyed\n",
        "  * 99.5% availability\n",
        "  * Use cases: storing secondary backup copiesof on-premises data\n",
        "* *S3 Glacier Instant Retrieval*\n",
        "  * Low cost object storage for archiving/backup\n",
        "  * Milliseconds retrieval\n",
        "  * Minimum storage duration of 90 days\n",
        "* *S3 Glacier Flexible Retrieval*\n",
        "  * Expedited (1-5 minutes), Standard (3-5 hours), Bulk (5-12 hours)\n",
        "  * Minimum storage duration of 90 days\n",
        "* *S3 Glacier Deep Archive*\n",
        "  * Standard (12 hours), Bulk (48 hours)\n",
        "  * Minimum storage duration of 180 days\n",
        "* S3 Intelligent Tiering*\n",
        "  * Small monthly monitoring and auto tiering fee\n",
        "  * Moves objects automatically between Access Tiers based on usage\n",
        "\n",
        "**AWS Snow Family**\n",
        "\n",
        "Highly-secure, portable devices to collect and process data at the edge, and migrate data into and out of AWS. Offline devices to perform data migrations\n",
        "\n",
        "* Data Migration:\n",
        "  * AWS Snowball Edge \n",
        "    * Physical data transport solution, move TBs or PBs of data in or out of AWS\n",
        "    * Altenative to moving data over the network \n",
        "    * Pay per data transfer job\n",
        "    * Types:\n",
        "      * Snowball Edge Storage Optimized: 80 TB of HDD capacity for block volume\n",
        "      * Snowball Edge Compute Optimized: 42 TB of HDD capacity for block volume\n",
        "    * Use cases: large data cloud migrations, disaster recovery  \n",
        "  * AWS Snowcone\n",
        "    * Small (2kg), portable computing, secure, withstands harsh environments   \n",
        "    * Used for edge computing, storage (8 TBs) and data transfer \n",
        "    * Use Snowcone when Snowball does not fit (space-constrained)\n",
        "    * Must provide your own battery\n",
        "  * AWS Snowmobile\n",
        "    * Transfer exabytes of data (1 EB = 1K PBs = 1M TBs)\n",
        "    * Each snowmobile has 100 PB of capacity\n",
        "    * High security: temperature controlled, GPS, 24/7 video surveillance\n",
        "    * Better than Snowball if you transfer more than 10 PB\n",
        "* Edge Computing:\n",
        "  * Process data while it's being created on an edge location (track, ship, etc...)\n",
        "  * These location may have no internet access or no easy access to computing power\n",
        "  * We setup a Snowball Edge/Snowcone device to do edge computing\n",
        "  * Use cases: Preprocess data, ML at the edge, transcoding media streams\n",
        "  * Types:\n",
        "    * Snowcone: 2 CPUs, 4GB of memory\n",
        "    * Snowball Edge - Compute Optimized: 52 CPUs, 208GB of RAM, optional GPU\n",
        "    * Snowball Edge - Storage Optimized: 40 CPUs, 80GB of RAM, object storage clustering available\n",
        "\n",
        "**AWS OpsHub**\n",
        "  * Historically to use Snow Family devices, you needed a CLI \n",
        "  * Today you can use OpsHub, a software you install on your computer, to manage your Snow Family devices\n",
        "\n",
        "**AWS Storage Gateway**\n",
        "* Bridge between on-premise data and cloud data in S3\n",
        "* Hybrid storage service to allow on-premises to seamlessly use the AWS Cloud\n",
        "* Use cases: disaster recovery, backup & restore, tiered storage      \n",
        "\n"
      ],
      "metadata": {
        "id": "ibeqmP9a0xJu"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 7. DATABASES SECTION"
      ],
      "metadata": {
        "id": "CQ6WOe7BWhm1"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Storing data on disk (EFS, EBS, EC2 Instance Store, S3) can have its limits. Sometimes you want to store data in a database to structure the data and build indexes to efficiently query/search through the data\n",
        "\n",
        "**Relational Databases**\n",
        "* AWS RDS (Relational Database Service)\n",
        "  * It's a managed DB service for DB use SQL asa query language\n",
        "  * It allows you to create databases in the cloud that are managed by AWS\n",
        "    * Postgres\n",
        "    * MySQL\n",
        "    * MariaDB\n",
        "    * Microsoft SQL Server\n",
        "    * AWS Aurora\n",
        "  * Automatic provisioning and OS patching\n",
        "  * Continuous backups and restore to specific timestamp\n",
        "  * Multi AZ for DR (disaster recovery)\n",
        "  * Scaling capability (vert & horiz)\n",
        "* AWS Aurora\n",
        "  * Not open sourced\n",
        "  * PostgreSQL and MySQL are both supported as Aurora DB\n",
        "  * Aurora is AWS cloud optimized\n",
        "  * Aurora storage automatically grows up to 64GB\n",
        "  * It costs more than RDS (20% more) but it's more efficient\n",
        "  * Not in the free tier\n",
        "\n",
        "**ElastiCache**\n",
        "* Same as RDS but for Redis or Memcached\n",
        "* Caches are in-memory databases with high performance and low latency\n",
        "* Helps reduce load off databases for read intensive workloads\n",
        "\n",
        "**DynamoDB**\n",
        "* Fully managed highly available with replication across 3 AZ\n",
        "* NoSQL database\n",
        "* Scales to massive db, distributed serverless db\n",
        "* Millions of requests per seconds, trillions of rows, 100s TB of storage\n",
        "* Single digit milliseconds latency\n",
        "* Integrated with IAM\n",
        "* Low cost and auto scaling\n",
        "* *DynamoDB Accelerator (DAX)*\n",
        "  * Fully managed in memory cache for DynamoDB\n",
        "  * 10x performance improvement \n",
        "  * Secure, highly scalable and available\n",
        "  * It's only used for and is integrated with DynamoDB\n",
        "\n",
        "**Redshift**\n",
        "* It's based on PostgreSQL but it's not for OLTP (Online Transaction Processing)\n",
        "* It's OLAP (Online Analytical Processing)\n",
        "* Load data every hour (not seconds)   \n",
        "* 10x better performance than other warehouses\n",
        "* Columnar storage of data (instead of rows)\n",
        "* Has SQL interface\n",
        "* BI (business intelligence) tools such as AWS Quicksight or Tableau integrate with it\n",
        "\n",
        "**Amazon EMR (Elastic MapReduce)**\n",
        "* EMR helps creating Hadoop clusters (Big Data) to analyze and process vast amount of data\n",
        "* The cluster can be made of hundreds of EC2 instances\n",
        "* Also supports Apache Spark, HBase, Presto, etc...\n",
        "* EMR takes care of all the provisioning and configuration\n",
        "* Use cases: data processing, ML, web indexing, big data, etc...\n",
        "\n",
        "**Amazon Athena**\n",
        "* Serverless query service to analyze data stored in Amazon S3\n",
        "* Uses standard SQL language to query the files\n",
        "* Supports CSV, JSON, ORC, Avro, etc...\n",
        "* Pricing: 5.00$ per TB of data scanned\n",
        "* Use compressed or columnar data for cost-savings\n",
        "\n",
        "**Amazon QuickSight**\n",
        "* Serverless ML powered business intelligence service to create interactive dashboards\n",
        "* Integrated with RDS, Aurora, Athena, RedShift, S3, etc...\n",
        "\n",
        "**DocumentDB**\n",
        "* It's Aurora but for MongoDB (NoSQL database)\n",
        "\n",
        "**Amazon Neptune**\n",
        "* Fully managed graph database\n",
        "* A popular graph database would be a social network, it's great for knowledge graph (wikipedia), fraud detection\n",
        "* Build and run applications working with highly connected datasets\n",
        "* Available across 3 AZ, with up to 15 read replicas\n",
        "\n",
        "**Amazon QLDB (Quantum Ledger Database)**\n",
        "* A ledger is a book recording financial transactions\n",
        "* Used to review history of all the changes made to your application data over time\n",
        "* Immutable system: noentry can be removed or modified, cryptographically verifiable\n",
        "* 2-3x better performance than common ledger\n",
        "\n",
        "**Amazon Managed Blockchain**\n",
        "* Blockchain makes it possible to build applications where multiple parties can execute transactions without the need for a trusted, central authority\n",
        "* Join public blockchain networks\n",
        "* Create your own scalable private network\n",
        "* Compatible with the frameworks Hyperledger Fabric and Ethereum \n",
        "\n",
        "**AWS Glue**\n",
        "* Managed extract, transform and load (ETL) service\n",
        "* Useful to prepare and transform data for analytics\n",
        "* Fully serverless service\n",
        "\n",
        "**DMS (Database Migration Service)**\n",
        "* Quickly and securely migrate databases to AWS, resilient and self healing\n",
        "* The source database remains available during the migration\n",
        "* Also supports heterogeneous migrations (e.g. Microsoft SQL Server to Aurora)\n"
      ],
      "metadata": {
        "id": "M9FBcZqsWmdD"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 8. OTHER COMPUTE SERVICES SECTION"
      ],
      "metadata": {
        "id": "jxD_zJGepoqH"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**Docker**\n",
        "* It's a software development platform to deploy apps\n",
        "* Apps are packaged in containers that can be run on any OS\n",
        "* Apps runs the same, regardless of where they run\n",
        "  * Any machine\n",
        "  * No compatibility issues\n",
        "  * Predictable behaviour\n",
        "  * Less work\n",
        "  * Works with any languages, any OS, any technology\n",
        "* Scale containers up and down very quickly (seconds)\n",
        "* Docker images are stored:\n",
        "  * Public: DockerHub\n",
        "  * Private: Amazon ECR (Elastic Container Registry)\n",
        "\n",
        "**ECS (Elastic Container Service)**\n",
        "    "
      ],
      "metadata": {
        "id": "An0JlA_WpvuF"
      }
    }
  ]
}